/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare class NativeSandbox {
  constructor(options?: object | undefined | null)
  exec(script: string): Promise<ExecResult>
  get fs(): SandboxFs
  stats(): Promise<SandboxStats>
  /**
   * Rescans the localVfs root directory and replaces quota usage with the
   * result. Call this after the host mutates the directory outside the
   * sandbox. Rejects when the sandbox was not built with the localVfs
   * option.
   */
  refreshLocalVfs(): Promise<VfsStatsJs>
  /**
   * Replaces localVfs quota usage with externally computed numbers, for
   * hosts that track usage out of band. Later file operations apply their
   * deltas on top of the pushed baseline and quota enforcement blocks
   * growth against it. Throws when the sandbox was not built with the
   * localVfs option.
   */
  setLocalVfsUsage(usage: VfsStatsJs): void
}
export type Sandbox = NativeSandbox

export declare class SandboxFs {
  stat(path: string): Promise<FileStat>
  readdir(path: string): Promise<Array<DirEntryJs>>
  mkdir(path: string): Promise<void>
  rename(from: string, to: string): Promise<void>
  unlink(path: string): Promise<void>
  rmdir(path: string): Promise<void>
  readFile(path: string): Promise<Buffer>
  writeFile(path: string, data: Buffer): Promise<void>
  appendFile(path: string, data: Buffer): Promise<void>
  open(path: string, mode: OpenModeJs): Promise<number>
  readAt(handle: number, offset: number, len: number): Promise<Buffer>
  writeAt(handle: number, offset: number, data: Buffer): Promise<number>
  truncate(handle: number, len: number): Promise<void>
  close(handle: number): Promise<void>
}

export interface CommandCall {
  args: Array<string>
  env: Record<string, string>
  cwd: string
  stdin: Buffer
}

export interface CommandOutput {
  exitCode?: number
  stdout?: Buffer
  stderr?: Buffer
}

export interface CommandTiming {
  name: string
  durationMs: number
  exitCode: number
}

export interface ConformanceResult {
  ok: boolean
  snapshots: string
}

export declare function createJsVfs(vfs: object): ExternalObject<JsVfsExternal>

export interface DirEntryJs {
  name: string
  fileType: string
  len: number
}

export interface ExecResult {
  stdout: string
  stderr: string
  exitCode: number
  wallTimeMs: number
  stdoutTruncated: boolean
  stderrTruncated: boolean
  pipeBytes: Array<number>
  commands: Array<CommandTiming>
  peakWasmMemoryBytes?: number
}

export interface FetchCallbackResponse {
  response?: FetchResponse
  error?: SyscallCallbackError
}

export interface FetchRequest {
  url: string
  method: string
  headers: Array<Array<string>>
  body?: Buffer
}

export interface FetchResponse {
  status?: number
  headers?: Array<Array<string>>
  body?: Buffer
}

export interface FileStat {
  fileType: string
  len: number
  isFile: boolean
  isDir: boolean
}

export interface OpenModeJs {
  read?: boolean
  write?: boolean
  create?: boolean
  createNew?: boolean
  truncate?: boolean
  append?: boolean
}

export const PROMPT_BUILTINS: string

export const PROMPT_FETCH: string

export const PROMPT_JQ: string

export const PROMPT_JS: string

export const PROMPT_OVERVIEW: string

export const PROMPT_SESSION_EPHEMERAL: string

export const PROMPT_SESSION_PERSISTENT: string

export const PROMPT_SHELL: string

export const PROMPT_SYSCALLS: string

export declare function runConformance(factory: (arg: [VfsQuotaJs]) => Promise<JsVfsHandle>): Promise<unknown>

export interface SandboxStats {
  commandsRun: number
  vfs?: VfsStatsJs
}

export interface SyscallCallbackError {
  message?: string
  code?: string
}

export interface SyscallCallbackResponse {
  value?: any
  error?: SyscallCallbackError
}

export interface VfsCallbackError {
  code?: string
  message?: string
}

export interface VfsQuotaJs {
  maxBytes: number
  maxFiles: number
  maxFileSize: number
}

export interface VfsRequest {
  path?: string
  from?: string
  to?: string
  mode?: OpenModeJs
  handle?: number
  offset?: number
  len?: number
  data?: Buffer
}

export interface VfsResponse {
  fileType?: string
  len?: number
  entries?: Array<DirEntryJs>
  handle?: number
  bytesRead?: number
  bytesWritten?: number
  data?: Buffer
  usedBytes?: number
  fileCount?: number
  error?: VfsCallbackError
}

export interface VfsStatsJs {
  usedBytes: number
  fileCount: number
}
